namespace Ecommerce.Api.Contracts.Analytics;

/// <summary>
/// Represents the main report generated by the AI agent.
/// </summary>
public class AiTrendReportDto
{
    public DateTime GeneratedAt { get; set; }
    public string Summary { get; set; } = string.Empty;
    public StrategicRecommendationsDto StrategicRecommendations { get; set; } = new();
    public List<SalesTrendPointDto> DailySalesTrend { get; set; } = new();
    public SalesForecastDto SalesForecast { get; set; } = new();
    public List<ProductPerformanceDto> TopPerformingProducts { get; set; } = new();
    public List<CategoryPerformanceDto> CategoryRevenueDistribution { get; set; } = new();
    public List<GeospatialPerformanceDto> GeospatialPerformance { get; set; } = new();
}

/// <summary>
/// A single data point for a sales trend chart.
/// </summary>
public class SalesTrendPointDto
{
    public DateTime Date { get; set; }
    public decimal TotalSales { get; set; }
}

/// <summary>
/// Contains performance metrics for a single product.
/// </summary>
public class ProductPerformanceDto
{
    public int ProductId { get; set; }
    public string ProductName { get; set; } = string.Empty;
    public int TotalQuantitySold { get; set; }
    public decimal TotalRevenue { get; set; }
}

/// <summary>
/// Contains performance metrics for a product category.
/// </summary>
public class CategoryPerformanceDto
{
    public string CategoryName { get; set; } = string.Empty;
    public decimal TotalRevenue { get; set; }
}

/// <summary>
/// Contains performance metrics for a geographic location.
/// </summary>
public class GeospatialPerformanceDto
{
    public string Location { get; set; } = string.Empty;
    public decimal TotalRevenue { get; set; }
    public int TotalSalesCount { get; set; }
}

/// <summary>
/// Contains the sales forecast.
/// </summary>
public class SalesForecastDto
{
    public decimal PredictedRevenue { get; set; }
    public string Trend { get; set; } = string.Empty;
}

/// <summary>
/// Contains strategic recommendations based on the 4 P's of Marketing.
/// </summary>
public class StrategicRecommendationsDto
{
    public string Product { get; set; } = string.Empty;
    public string Price { get; set; } = string.Empty;
    public string Place { get; set; } = string.Empty;
    public string Promotion { get; set; } = string.Empty;
}
